"""empty message

Revision ID: c50e0ef04c04
Revises: 
Create Date: 2023-09-26 01:37:09.531046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50e0ef04c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phishing_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('sender', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_phishing', sa.Enum('genuine', 'phishing', 'unsure'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('last_challenge_id', sa.String(length=36), nullable=True),
    sa.Column('current_challenge_id', sa.String(length=36), nullable=True),
    sa.Column('has_completed_simulation', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('grade_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['current_challenge_id'], ['phishing_challenges.id'], ),
    sa.ForeignKeyConstraint(['last_challenge_id'], ['phishing_challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post_simulation_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('awareness', sa.String(length=64), nullable=False),
    sa.Column('ratings', sa.Integer(), nullable=False),
    sa.Column('helpful', sa.String(length=64), nullable=False),
    sa.Column('act', sa.String(length=64), nullable=False),
    sa.Column('behaviour', sa.String(length=64), nullable=False),
    sa.Column('effective', sa.String(length=64), nullable=False),
    sa.Column('life', sa.String(length=64), nullable=False),
    sa.Column('recommend', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_simulation_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=64), nullable=False),
    sa.Column('training', sa.String(length=64), nullable=False),
    sa.Column('knowledge', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('actions', sa.String(length=64), nullable=False),
    sa.Column('consequences', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_progress_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_score', sa.Integer(), nullable=True),
    sa.Column('grade_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phishing_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('challenge_number', sa.Integer(), nullable=False),
    sa.Column('clicked_link', sa.Boolean(), nullable=False),
    sa.Column('phishing', sa.Enum('genuine', 'phishing', 'unsure'), nullable=False),
    sa.Column('confidence', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=64), nullable=False),
    sa.Column('pre_simulation_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['phishing_challenges.id'], ),
    sa.ForeignKeyConstraint(['pre_simulation_id'], ['pre_simulation_responses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phishing_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phishing_responses_challenge_id'), ['challenge_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phishing_responses_challenge_id'))

    op.drop_table('phishing_responses')
    op.drop_table('user_progress_log')
    op.drop_table('pre_simulation_responses')
    op.drop_table('post_simulation_responses')
    op.drop_table('users')
    op.drop_table('phishing_challenges')
    # ### end Alembic commands ###
